server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  # gateway configuration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # gateway routes configuration
      routes:
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/v1/drivers/**
        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers/**
        - id: rides-service
          uri: lb://rides-service
          predicates:
            - Path=/api/v1/rides/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/rating/**

# swagger routes configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: api-gateway
        url: /v3/api-docs
      - name: driver-service
        url: /api/v1/drivers/v3/api-docs
      - name: passenger-service
        url: /api/v1/passengers/v3/api-docs
      - name: rides-service
        url: /api/v1/rides/v3/api-docs
      - name: payment-service
        url: /api/v1/payment/v3/api-docs
      - name: rating-service
        url: /api/v1/rating/v3/api-docs