server:
  port: 8086

spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
  web:
    locale-resolver: accept_header
    locale: en
  application:
    name: rides-service
  # postgresql database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/taxi_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: false
  # liquibase configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

# swagger routes configuration
springdoc:
  api-docs:
    enabled: true
    path: /api/v1/rides/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/v1/rides/swagger-ui.html