server:
  port: 8090

spring:
  application:
    name: rating-service
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
  web:
    locale-resolver: accept_header
    locale: en
  # mongodb database configuration
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/taxi_db
  # liquibase configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

# swagger routes configuration
springdoc:
  api-docs:
    enabled: true
    path: /api/v1/ratings/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/v1/ratings/swagger-ui.html