server:
  port: 8090

spring:
  application:
    name: rating-service
  # liquibase configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  # mongodb database configuration
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/taxi_db

# swagger routes configuration
springdoc:
  api-docs:
    enabled: true
    path: /api/v1/rating/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/v1/rating/swagger-ui.html