server:
  port: 8090

spring:
  application:
    name: rating-service
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
  web:
    locale-resolver: accept_header
    locale: en
  # postgresql database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/taxi_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: false
  # liquibase configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  # mongodb database configuration
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/taxi_db
  #kafka configuration
  kafka:
    producer:
      bootstrap-servers: localhost:9092, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery:
          timeout:
            ms: 100000
        linger:
            ms: 0
        request:
          timeout:
            ms: 20000
        enable:
          idempotence: true
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5

# swagger routes configuration
springdoc:
  api-docs:
    enabled: true
    path: /api/v1/ratings/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/v1/ratings/swagger-ui.html