server:
  port: 8088

spring:
  application:
    name: payment-service
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
  web:
    locale-resolver: accept_header
    locale: en
  # postgresql database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/taxi_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: false
  # liquibase configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  # mongodb database configuration
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/taxi_db
  artemis:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    mode: native

# swagger routes configuration
springdoc:
  api-docs:
    enabled: true
    path: /api/v1/payments/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/v1/payments/swagger-ui.html